apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ci2s8ft0k-java-quarkus
  janus-idp.io/tekton: ci2s8ft0k-java-quarkus
  backstage.io/kubernetes-id: ci2s8ft0k-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ci2s8ft0k-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
